using System.Collections.Generic;
using NUnit.Framework;
using ThreeKingdoms.EditorTools;
using UnityEditor;
using UnityEngine;
using UnityEngine.TestTools;

namespace ThreeKingdoms.Tests.EditMode
{
    public sealed class BattleEditorEditModeTests
    {
        private const string Skill1Path = "Assets/Data/Combat/Actions/Diaochan/DIA_Skill1.asset";
        [Test] public void BattleEditor_CanOpen(){LogAssert.ignoreFailingMessages=true;try{var w=ThreeKingdomsBattleEditorWindow.Open();Assert.NotNull(w);w.Close();}finally{LogAssert.ignoreFailingMessages=false;}}
        [Test] public void BattleEditor_LoadCharacter(){var lib=AssetDatabase.LoadAssetAtPath<CharacterActionLibrary>("Assets/Data/Combat/Actions/LIB_Diaochan.asset");Assert.AreEqual("Diaochan",lib.ownerId);Assert.Greater(lib.actions.Count,0);}
        [Test] public void BattleEditor_LoadAction(){Assert.NotNull(AssetDatabase.LoadAssetAtPath<ActionDefinition>(Skill1Path));}
        [Test] public void BattleEditor_ReadAnimationFrames(){var a=AssetDatabase.LoadAssetAtPath<ActionDefinition>(Skill1Path);Assert.AreEqual(a.frameCount,ActionEditorUtility.ReadAnimationFrames(a.animation).Count);Assert.Greater(a.frameCount,1);}
        [Test] public void BattleEditor_FrameNavigation(){var a=AssetDatabase.LoadAssetAtPath<ActionDefinition>(Skill1Path);Assert.AreEqual(a.frameCount-1,a.ClampFrame(999));Assert.AreEqual(0,a.ClampFrame(-1));}
        [Test] public void BattleEditor_CreateBoxHitbox(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.frameCount=3;Assert.AreEqual(ActionShapeType.Box,ActionEditorUtility.CreateBox(a,1,ActionShapeRole.DamageHitbox,Vector2.one,Vector2.one).shapeType);Object.DestroyImmediate(a);}
        [Test] public void BattleEditor_CreatePolygonHitbox(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.frameCount=3;var s=ActionEditorUtility.CreatePolygon(a,1,ActionShapeRole.EffectHitbox,new[]{Vector2.zero,Vector2.right,Vector2.up});Assert.AreEqual(3,s.points.Count);Object.DestroyImmediate(a);}
        [Test] public void BattleEditor_SaveAction(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.id="SaveProbe";string json=EditorJsonUtility.ToJson(a);Assert.That(json,Does.Contain("SaveProbe"));Object.DestroyImmediate(a);}
        [Test] public void BattleEditor_Undo(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.id="A";Undo.RecordObject(a,"Probe");a.id="B";Undo.PerformUndo();Assert.AreEqual("A",a.id);Object.DestroyImmediate(a);}
        [Test] public void BattleEditor_ValidateAction(){var a=AssetDatabase.LoadAssetAtPath<ActionDefinition>(Skill1Path);Assert.That(ActionEditorUtility.ValidateAction(a),Has.None.StartsWith("ERROR"));}
        [Test] public void BattleEditor_FacingMirror(){Assert.AreEqual(new Vector2(-2,1),ActionGeometry.Mirror(new Vector2(2,1),-1));}
        [Test] public void BattleEditor_ActionDamageSettingsAreIndependent(){var first=ScriptableObject.CreateInstance<ActionDefinition>();var second=ScriptableObject.CreateInstance<ActionDefinition>();first.combat.damage=7f;second.combat.damage=31f;Assert.AreEqual(7f,first.combat.damage);Assert.AreEqual(31f,second.combat.damage);Object.DestroyImmediate(first);Object.DestroyImmediate(second);}
        [Test] public void BattleEditor_CombatDraftCloneDoesNotMutateSource(){var source=new ActionCombatData{damage=12f};var draft=source.Clone();draft.damage=99f;Assert.AreEqual(12f,source.damage);Assert.AreEqual(99f,draft.damage);}
        [Test] public void BattleEditor_ShapeDamageOverrideIsCloned(){var shape=new ActionFrameShape{overrideDamage=true,damage=17f};var clone=shape.Clone();clone.damage=23f;Assert.AreEqual(17f,shape.EffectiveDamage(5f));Assert.AreEqual(23f,clone.EffectiveDamage(5f));}
        [Test] public void BattleEditor_PerFrameVisualOffsetIsIndependentAndResettable(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.frameCount=4;a.SetVisualOffset(2,new Vector2(.25f,-.4f));Assert.AreEqual(Vector2.zero,a.VisualOffsetAt(1));Assert.AreEqual(new Vector2(.25f,-.4f),a.VisualOffsetAt(2));a.SetVisualOffset(2,Vector2.zero);Assert.AreEqual(Vector2.zero,a.VisualOffsetAt(2));Assert.AreEqual(0,a.frameVisualOffsets.Count);Object.DestroyImmediate(a);}
        [Test] public void BattleEditor_AllCharactersPersistExactFramesAsActionData(){AllCharacterActionFrameSync.SyncAllNow();foreach(string owner in new[]{"Diaochan","Soldier","CaoCao"}){var library=AssetDatabase.LoadAssetAtPath<CharacterActionLibrary>($"Assets/Data/Combat/Actions/LIB_{owner}.asset");Assert.That(library,Is.Not.Null,owner);foreach(ActionDefinition action in library.actions){if(action==null||action.animation==null)continue;List<Sprite> frames=ActionEditorUtility.ReadAnimationFrames(action.animation);if(frames.Count==0)continue;Assert.That(action.visualFrames.Count,Is.EqualTo(frames.Count),$"{owner}/{action.id} exact frames");for(int i=0;i<frames.Count;i++)Assert.That(action.visualFrames[i],Is.SameAs(frames[i]),$"{owner}/{action.id} frame {i}");}}}
        [Test] public void BattleEditor_EmbeddedTestCalculatesRealShapeDamage(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.id="EmbeddedProbe";a.displayName="Embedded Probe";a.frameCount=3;a.framesPerSecond=10;a.animation=new AnimationClip();a.combat.damage=13f;a.combat.hitPolicy=ActionHitPolicy.OncePerAction;a.frameShapes.Add(new ActionFrameShape{frame=1,role=ActionShapeRole.DamageHitbox,center=new Vector2(1f,1.1f),size=new Vector2(1.5f,2f)});var w=ThreeKingdomsBattleEditorWindow.Open();try{w.SelectAction(a);w.RunEmbeddedTestFrameForTest(1,1f);Assert.AreEqual(1,w.EmbeddedTestHitCount);Assert.AreEqual(13f,w.EmbeddedTestTotalDamage,.001f);}finally{w.Close();Object.DestroyImmediate(a);}}
        [Test] public void BattleEditor_SafeImportPreservesExistingAuthoredAction(){var action=AssetDatabase.LoadAssetAtPath<ActionDefinition>(Skill1Path);string before=EditorJsonUtility.ToJson(action);BattleEditorMigration.MigrateExistingCombatData();var after=AssetDatabase.LoadAssetAtPath<ActionDefinition>(Skill1Path);Assert.AreEqual(before,EditorJsonUtility.ToJson(after));}
        [Test] public void BattleEditor_ConvertsLegacyComboWindowsToAnimationFrames(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.frameCount=25;a.framesPerSecond=15f;a.combo.Add(new ActionComboSegment{startFrame=0,hitStartFrame=8,hitEndFrame=17,comboWindowStart=17,comboWindowEnd=21,endFrame=21});a.combo.Add(new ActionComboSegment{startFrame=21,hitStartFrame=25,hitEndFrame=34,comboWindowStart=34,comboWindowEnd=38,endFrame=24});a.combo.Add(new ActionComboSegment{startFrame=38,hitStartFrame=42,hitEndFrame=50,comboWindowStart=50,comboWindowEnd=59,endFrame=24});a.combo.Add(new ActionComboSegment{startFrame=59,hitStartFrame=63,hitEndFrame=76,comboWindowStart=71,comboWindowEnd=84,endFrame=24});Assert.IsTrue(ActionEditorUtility.HasLegacyComboFrames(a));ActionEditorUtility.ConvertLegacyComboFrames(a);Assert.IsFalse(ActionEditorUtility.HasLegacyComboFrames(a));Assert.AreEqual(5,a.combo[1].startFrame);Assert.AreEqual(24,a.combo[3].endFrame);Object.DestroyImmediate(a);}
        [Test] public void BattleEditor_TightSpritePreviewUsesTextureRectLocalPivot(){var sprite=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/Characters/SoldierReplacement/AttackFrames/NSOL_Attack_000.png");Assert.NotNull(sprite);Assert.That(sprite.textureRectOffset.x,Is.GreaterThan(100f),"fixture must retain the large transparent left margin that exposed the preview bug");Vector2 previewPivot=ThreeKingdomsBattleEditorWindow.PreviewTexturePivot(sprite);Assert.That(Vector2.Distance(previewPivot+sprite.textureRectOffset,sprite.pivot),Is.LessThan(.0001f));Assert.That(previewPivot.x,Is.LessThan(sprite.pivot.x),"preview must not apply the full-canvas pivot to the trimmed textureRect");}
        [Test] public void BattleEditor_LightAndHeavyReactionSettingsAreIndependent(){var a=ScriptableObject.CreateInstance<ActionDefinition>();a.reaction.light.stunDuration=.2f;a.reaction.light.retreatDistance=.1f;a.reaction.heavy.stunDuration=.6f;a.reaction.heavy.retreatDistance=.8f;Assert.AreEqual(.2f,a.reaction.light.stunDuration);Assert.AreEqual(.1f,a.reaction.light.retreatDistance);Assert.AreEqual(.6f,a.reaction.heavy.stunDuration);Assert.AreEqual(.8f,a.reaction.heavy.retreatDistance);Object.DestroyImmediate(a);}
        [Test] public void BattleEditor_SoldierReactionAssetPersistsDirectRetreatDistances(){var a=AssetDatabase.LoadAssetAtPath<ActionDefinition>("Assets/Data/Combat/Actions/Soldier/SOL_HitReact.asset");Assert.NotNull(a);Assert.NotNull(a.reaction);Assert.AreEqual(0f,a.reaction.light.retreatDistance);Assert.AreEqual(.45f,a.reaction.heavy.retreatDistance,.001f);}
    }
}
